insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Centro Escolar España', ' Avenida Don Bosco, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Centro Escolar Catolico Nuestra Señora de Santa Ana', '17 Avenida Sur, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Jorge Lardé Centro Escolar', 'Decima Avenida Sur y Calle Ramón Belloso, #510, San Jacinto, San Salvador, 10 Ave sur 510, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Heart Catholic School Center Mary', 'Calle Sevilla, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Centro Escolar Católico Santa Catalina', 'Avenida Cuba y Calle Ramón Belloso, #629, Avenida Cuba 629, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('General Francisco Morazán School', 'FINAL, 25 Av Norte, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Centro Escolar General Ramon Belloso', 'Ave Alicante, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Centro Escolar "Dr. Darío González"', 'Calle Los Tanques, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Centro Escolar Francisco A Gamboa', '5 Calle Ote 726, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Centro Escolar Católico Pablo VI', 'Final 39 Avenida Sur, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Centro Escolar República de Panamá', '20 Avenida Norte, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Colegio Internacional de San Salvador', 'Calle La Reforma, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Colegio Americano of El Salvador', 'Colonia Lomas de San Francisco, Calle N1 Local 2, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Highlands Colegio San Salvador', 'Carretera Panamericana Carretera a Santa Tecla Final, Pasaje Privado D, Santa Tecla', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Colegio Bilingüe Maquilishuat', ' Bulevar Del Hipodromo, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Eucativo center "Joyas de Ceren"', '1a Calle Pte &, 63 Av Norte, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Adventist College of San Salvador', '1a Avenida Norte, San Salvado', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Salvadoran Spanish school', 'Pje Caribe, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Colegio Externado San José', '33ª av. norte, final pje. San José, res. Decápolis, San Salvador, República de El Salvador.', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Colegio San Pablo', 'Col. Escalon final 5 Calle Poniente y, Calle Jose Martî, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Colegio Guadalupano', 'Col. Medica 25 Av Nte. y final 27 Av Nte # 1047,, San Salvador', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Colegio Champagnat', '7 Avenida Norte, Santa Tecla', 193, true);
insert into public.centroescolar (centroescolarname, direccion, municipioid, estado) values ('Centro Escolar España', ' Avenida Don Bosco, San Salvador', 193, true);
