insert into public.materia (materianame, descripcion, estado) values ('ADMINISTRACION DE COSTOS', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('ANALISIS DE CUENTAS NACIONALES', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('ANALISIS ESTRATEGICO', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('ANALISIS Y EVALUACION DE SISTEMAS INFORMATICOS', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('AUDITORIA II', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('AUDITORIA INTERNA', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('CINE', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('CONTABILIDAD BANCARIA', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('CONTABILIDAD FINANCIERA I', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('DIRECCION ESTRATEGICA', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('ESTADISTICA APLICADA', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('ESTADISTICA I', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('FILOSOFIA I', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('ANTROPOLOGIA TEOLOGICA', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('BASES BIOLOGICAS DEL COMPORTAMIENTO I', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('CRISTOLOGIA', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('CAMBIO CLIMATICO Y CIUDAD', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('DERECHO LABORAL I', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('ADMINISTRACION Y CONTROL DE CALIDAD', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('ANALISIS NUMERICO', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('ANALISIS DE SISTEMAS', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('ALGEBRA VECTORIAL Y MATRICES', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('BASES DE DATOS', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('COMUNICACIONES I', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('DINAMICA', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('ELECTRICIDAD Y MAGNETISMO', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('FISICA I', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('FISICA II', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('FORMULACION Y EVALUACION DE PROYECTOS', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('FUNDAMENTOS DE PROGRAMACION', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('MATEMATICA I (ING)', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('MATEMATICA DISCRETA I', 'Descripcion', true);
insert into public.materia (materianame, descripcion, estado) values ('SIMULACION', 'Descripcion', false);
insert into public.materia (materianame, descripcion, estado) values ('TECNICAS DE REDACCION', 'Descripcion', true);
