insert into public.municipio (municipioname, departamentoid) values (' Ahuachapán', 1);
insert into public.municipio (municipioname, departamentoid) values (' Apaneca', 1);
insert into public.municipio (municipioname, departamentoid) values (' Atiquizaya', 1);
insert into public.municipio (municipioname, departamentoid) values (' Concepción de Ataco', 1);
insert into public.municipio (municipioname, departamentoid) values (' El Refugio', 1);
insert into public.municipio (municipioname, departamentoid) values (' Guaymango', 1);
insert into public.municipio (municipioname, departamentoid) values (' Jujutla', 1);
insert into public.municipio (municipioname, departamentoid) values (' San Francisco Menéndez', 1);
insert into public.municipio (municipioname, departamentoid) values (' San Lorenzo', 1);
insert into public.municipio (municipioname, departamentoid) values (' San Pedro Puxtla', 1);
insert into public.municipio (municipioname, departamentoid) values (' Tacuba', 1);
insert into public.municipio (municipioname, departamentoid) values (' Turín', 1);
insert into public.municipio (municipioname, departamentoid) values (' Cinquera', 2);
insert into public.municipio (municipioname, departamentoid) values (' Dolores', 2);
insert into public.municipio (municipioname, departamentoid) values (' Guacotecti', 2);
insert into public.municipio (municipioname, departamentoid) values (' Ilobasco', 2);
insert into public.municipio (municipioname, departamentoid) values (' Jutiapa', 2);
insert into public.municipio (municipioname, departamentoid) values (' San Isidro', 2);
insert into public.municipio (municipioname, departamentoid) values (' Sensuntepeque', 2);
insert into public.municipio (municipioname, departamentoid) values (' Tejutepeque', 2);
insert into public.municipio (municipioname, departamentoid) values (' Victoria', 2);
insert into public.municipio (municipioname, departamentoid) values (' Agua Caliente', 3);
insert into public.municipio (municipioname, departamentoid) values (' Arcatao', 3);
insert into public.municipio (municipioname, departamentoid) values (' Azacualpa', 3);
insert into public.municipio (municipioname, departamentoid) values (' Chalatenango', 3);
insert into public.municipio (municipioname, departamentoid) values (' Citalá', 3);
insert into public.municipio (municipioname, departamentoid) values (' Comalapa', 3);
insert into public.municipio (municipioname, departamentoid) values (' Concepción Quezaltepeque', 3);
insert into public.municipio (municipioname, departamentoid) values (' Dulce Nombre de María', 3);
insert into public.municipio (municipioname, departamentoid) values (' El Carrizal', 3);
insert into public.municipio (municipioname, departamentoid) values (' El Paraíso', 3);
insert into public.municipio (municipioname, departamentoid) values (' La Laguna', 3);
insert into public.municipio (municipioname, departamentoid) values (' La Palma', 3);
insert into public.municipio (municipioname, departamentoid) values (' La Reina', 3);
insert into public.municipio (municipioname, departamentoid) values (' Las Vueltas', 3);
insert into public.municipio (municipioname, departamentoid) values (' Nombre de Jesús', 3);
insert into public.municipio (municipioname, departamentoid) values (' Nueva Concepción', 3);
insert into public.municipio (municipioname, departamentoid) values (' Nueva Trinidad', 3);
insert into public.municipio (municipioname, departamentoid) values (' Ojos de Agua', 3);
insert into public.municipio (municipioname, departamentoid) values (' Potonico', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Antonio de la Cruz (San Antonio La Cruz)', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Antonio Los Ranchos (San Antonio Ranchos)', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Fernando', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Francisco Lempa', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Francisco Morazán', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Ignacio', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Isidro Labrador', 3);
insert into public.municipio (municipioname, departamentoid) values (' San José Cancasque', 3);
insert into public.municipio (municipioname, departamentoid) values (' San José Las Flores', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Luis del Carmen', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Miguel de Mercedes', 3);
insert into public.municipio (municipioname, departamentoid) values (' San Rafael', 3);
insert into public.municipio (municipioname, departamentoid) values (' Santa Rita', 3);
insert into public.municipio (municipioname, departamentoid) values (' Tejutla', 3);
insert into public.municipio (municipioname, departamentoid) values (' Candelaria', 4);
insert into public.municipio (municipioname, departamentoid) values (' Cojutepeque', 4);
insert into public.municipio (municipioname, departamentoid) values (' El Carmen', 4);
insert into public.municipio (municipioname, departamentoid) values (' El Rosario', 4);
insert into public.municipio (municipioname, departamentoid) values (' Monte San Juan', 4);
insert into public.municipio (municipioname, departamentoid) values (' Oratorio de Concepción', 4);
insert into public.municipio (municipioname, departamentoid) values (' San Bartolomé Perulapía', 4);
insert into public.municipio (municipioname, departamentoid) values (' San Cristóbal', 4);
insert into public.municipio (municipioname, departamentoid) values (' San José Guayabal', 4);
insert into public.municipio (municipioname, departamentoid) values (' San Pedro Perulapán', 4);
insert into public.municipio (municipioname, departamentoid) values (' San Rafael Cedros', 4);
insert into public.municipio (municipioname, departamentoid) values (' San Ramón', 4);
insert into public.municipio (municipioname, departamentoid) values (' Santa Cruz Analquito', 4);
insert into public.municipio (municipioname, departamentoid) values (' Santa Cruz Michapa', 4);
insert into public.municipio (municipioname, departamentoid) values (' Suchitoto', 4);
insert into public.municipio (municipioname, departamentoid) values (' Tenancingo', 4);
insert into public.municipio (municipioname, departamentoid) values (' Antiguo Cuscatlán', 5);
insert into public.municipio (municipioname, departamentoid) values (' Chiltiupán', 5);
insert into public.municipio (municipioname, departamentoid) values (' Ciudad Arce', 5);
insert into public.municipio (municipioname, departamentoid) values (' Colón', 5);
insert into public.municipio (municipioname, departamentoid) values (' Comasagua', 5);
insert into public.municipio (municipioname, departamentoid) values (' Huizúcar', 5);
insert into public.municipio (municipioname, departamentoid) values (' Jayaque', 5);
insert into public.municipio (municipioname, departamentoid) values (' Jicalapa', 5);
insert into public.municipio (municipioname, departamentoid) values (' La Libertad', 5);
insert into public.municipio (municipioname, departamentoid) values (' Nuevo Cuscatlán', 5);
insert into public.municipio (municipioname, departamentoid) values (' Opico', 5);
insert into public.municipio (municipioname, departamentoid) values (' Quezaltepeque', 5);
insert into public.municipio (municipioname, departamentoid) values (' Sacacoyo', 5);
insert into public.municipio (municipioname, departamentoid) values (' San José Villanueva', 5);
insert into public.municipio (municipioname, departamentoid) values (' San Matías', 5);
insert into public.municipio (municipioname, departamentoid) values (' San Pablo Tacachico', 5);
insert into public.municipio (municipioname, departamentoid) values (' Santa Tecla', 5);
insert into public.municipio (municipioname, departamentoid) values (' Talnique', 5);
insert into public.municipio (municipioname, departamentoid) values (' Tamanique', 5);
insert into public.municipio (municipioname, departamentoid) values (' Teotepeque', 5);
insert into public.municipio (municipioname, departamentoid) values (' Tepecoyo', 5);
insert into public.municipio (municipioname, departamentoid) values (' Zaragoza', 5);
insert into public.municipio (municipioname, departamentoid) values (' Cuyultitán', 6);
insert into public.municipio (municipioname, departamentoid) values (' El Rosario', 6);
insert into public.municipio (municipioname, departamentoid) values (' Jerusalén', 6);
insert into public.municipio (municipioname, departamentoid) values (' Mercedes La Ceiba', 6);
insert into public.municipio (municipioname, departamentoid) values (' Olocuilta', 6);
insert into public.municipio (municipioname, departamentoid) values (' Paraíso de Osorio', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Antonio Masahuat', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Emigdio', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Francisco Chinameca', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Juan Nonualco', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Juan Talpa', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Juan Tepezontes', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Luis La Herradura', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Luis Talpa', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Miguel Tepezontes', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Pedro Masahuat', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Pedro Nonualco', 6);
insert into public.municipio (municipioname, departamentoid) values (' San Rafael Obrajuelo', 6);
insert into public.municipio (municipioname, departamentoid) values (' Santa María Ostuma', 6);
insert into public.municipio (municipioname, departamentoid) values (' Santiago Nonualco', 6);
insert into public.municipio (municipioname, departamentoid) values (' Tapalhuaca', 6);
insert into public.municipio (municipioname, departamentoid) values (' Zacatecoluca', 6);
insert into public.municipio (municipioname, departamentoid) values (' Anamorós', 7);
insert into public.municipio (municipioname, departamentoid) values (' Bolívar', 7);
insert into public.municipio (municipioname, departamentoid) values (' Concepción de Oriente', 7);
insert into public.municipio (municipioname, departamentoid) values (' Conchagua', 7);
insert into public.municipio (municipioname, departamentoid) values (' El Carmen', 7);
insert into public.municipio (municipioname, departamentoid) values (' El Sauce', 7);
insert into public.municipio (municipioname, departamentoid) values (' Intipucá', 7);
insert into public.municipio (municipioname, departamentoid) values (' La Unión', 7);
insert into public.municipio (municipioname, departamentoid) values (' Lislique', 7);
insert into public.municipio (municipioname, departamentoid) values (' Meanguera del Golfo', 7);
insert into public.municipio (municipioname, departamentoid) values (' Nueva Esparta', 7);
insert into public.municipio (municipioname, departamentoid) values (' Pasaquina', 7);
insert into public.municipio (municipioname, departamentoid) values (' Polorós', 7);
insert into public.municipio (municipioname, departamentoid) values (' San Alejo', 7);
insert into public.municipio (municipioname, departamentoid) values (' San José', 7);
insert into public.municipio (municipioname, departamentoid) values (' Santa Rosa de Lima', 7);
insert into public.municipio (municipioname, departamentoid) values (' Yayantique', 7);
insert into public.municipio (municipioname, departamentoid) values (' Yucuaiquín', 7);
insert into public.municipio (municipioname, departamentoid) values (' Arambala', 8);
insert into public.municipio (municipioname, departamentoid) values (' Cacaopera', 8);
insert into public.municipio (municipioname, departamentoid) values (' Chilanga', 8);
insert into public.municipio (municipioname, departamentoid) values (' Corinto', 8);
insert into public.municipio (municipioname, departamentoid) values (' Delicias de Concepción', 8);
insert into public.municipio (municipioname, departamentoid) values (' El Divisadero', 8);
insert into public.municipio (municipioname, departamentoid) values (' El Rosario', 8);
insert into public.municipio (municipioname, departamentoid) values (' Gualococti', 8);
insert into public.municipio (municipioname, departamentoid) values (' Guatajiagua', 8);
insert into public.municipio (municipioname, departamentoid) values (' Joateca', 8);
insert into public.municipio (municipioname, departamentoid) values (' Jocoaitique', 8);
insert into public.municipio (municipioname, departamentoid) values (' Jocoro', 8);
insert into public.municipio (municipioname, departamentoid) values (' Lolotiquillo', 8);
insert into public.municipio (municipioname, departamentoid) values (' Meanguera', 8);
insert into public.municipio (municipioname, departamentoid) values (' Osicala', 8);
insert into public.municipio (municipioname, departamentoid) values (' Perquín', 8);
insert into public.municipio (municipioname, departamentoid) values (' San Carlos', 8);
insert into public.municipio (municipioname, departamentoid) values (' San Fernando', 8);
insert into public.municipio (municipioname, departamentoid) values (' San Francisco Gotera', 8);
insert into public.municipio (municipioname, departamentoid) values (' San Isidro', 8);
insert into public.municipio (municipioname, departamentoid) values (' San Simón', 8);
insert into public.municipio (municipioname, departamentoid) values (' Sensembra', 8);
insert into public.municipio (municipioname, departamentoid) values (' Sociedad', 8);
insert into public.municipio (municipioname, departamentoid) values (' Torola', 8);
insert into public.municipio (municipioname, departamentoid) values (' Yamabal', 8);
insert into public.municipio (municipioname, departamentoid) values (' Yoloaiquín', 8);
insert into public.municipio (municipioname, departamentoid) values (' Carolina', 9);
insert into public.municipio (municipioname, departamentoid) values (' Chapeltique', 9);
insert into public.municipio (municipioname, departamentoid) values (' Chinameca', 9);
insert into public.municipio (municipioname, departamentoid) values (' Chirilagua', 9);
insert into public.municipio (municipioname, departamentoid) values (' Ciudad Barrios', 9);
insert into public.municipio (municipioname, departamentoid) values (' Comacarán', 9);
insert into public.municipio (municipioname, departamentoid) values (' El Tránsito', 9);
insert into public.municipio (municipioname, departamentoid) values (' Lolotique', 9);
insert into public.municipio (municipioname, departamentoid) values (' Moncagua', 9);
insert into public.municipio (municipioname, departamentoid) values (' Nueva Guadalupe', 9);
insert into public.municipio (municipioname, departamentoid) values (' Nuevo Edén de San Juan', 9);
insert into public.municipio (municipioname, departamentoid) values (' Quelepa', 9);
insert into public.municipio (municipioname, departamentoid) values (' San Antonio', 9);
insert into public.municipio (municipioname, departamentoid) values (' San Gerardo', 9);
insert into public.municipio (municipioname, departamentoid) values (' San Jorge', 9);
insert into public.municipio (municipioname, departamentoid) values (' San Luis de la Reina', 9);
insert into public.municipio (municipioname, departamentoid) values (' San Miguel', 9);
insert into public.municipio (municipioname, departamentoid) values (' San Rafael (San Rafael Oriente)', 9);
insert into public.municipio (municipioname, departamentoid) values (' Sesori', 9);
insert into public.municipio (municipioname, departamentoid) values (' Uluazapa', 9);
insert into public.municipio (municipioname, departamentoid) values (' Aguilares', 10);
insert into public.municipio (municipioname, departamentoid) values (' Apopa', 10);
insert into public.municipio (municipioname, departamentoid) values (' Ayutuxtepeque', 10);
insert into public.municipio (municipioname, departamentoid) values (' Cuscatancingo', 10);
insert into public.municipio (municipioname, departamentoid) values (' Delgado', 10);
insert into public.municipio (municipioname, departamentoid) values (' El Paisnal', 10);
insert into public.municipio (municipioname, departamentoid) values (' Guazapa', 10);
insert into public.municipio (municipioname, departamentoid) values (' Ilopango', 10);
insert into public.municipio (municipioname, departamentoid) values (' Mejicanos', 10);
insert into public.municipio (municipioname, departamentoid) values (' Nejapa', 10);
insert into public.municipio (municipioname, departamentoid) values (' Panchimalco', 10);
insert into public.municipio (municipioname, departamentoid) values (' Rosario de Mora', 10);
insert into public.municipio (municipioname, departamentoid) values (' San Marcos', 10);
insert into public.municipio (municipioname, departamentoid) values (' San Martín', 10);
insert into public.municipio (municipioname, departamentoid) values (' San Salvador', 10);
insert into public.municipio (municipioname, departamentoid) values (' Santiago Texacuangos', 10);
insert into public.municipio (municipioname, departamentoid) values (' Santo Tomás', 10);
insert into public.municipio (municipioname, departamentoid) values (' Soyapango', 10);
insert into public.municipio (municipioname, departamentoid) values (' Tonacatepeque', 10);
insert into public.municipio (municipioname, departamentoid) values (' Apastepeque', 11);
insert into public.municipio (municipioname, departamentoid) values (' Guadalupe', 11);
insert into public.municipio (municipioname, departamentoid) values (' San Cayetano Istepeque', 11);
insert into public.municipio (municipioname, departamentoid) values (' San Esteban Catarina', 11);
insert into public.municipio (municipioname, departamentoid) values (' San Ildefonso', 11);
insert into public.municipio (municipioname, departamentoid) values (' San Lorenzo', 11);
insert into public.municipio (municipioname, departamentoid) values (' San Sebastián', 11);
insert into public.municipio (municipioname, departamentoid) values (' San Vicente', 11);
insert into public.municipio (municipioname, departamentoid) values (' Santa Clara', 11);
insert into public.municipio (municipioname, departamentoid) values (' Santo Domingo', 11);
insert into public.municipio (municipioname, departamentoid) values (' Tecoluca', 11);
insert into public.municipio (municipioname, departamentoid) values (' Tepetitán', 11);
insert into public.municipio (municipioname, departamentoid) values (' Verapaz', 11);
insert into public.municipio (municipioname, departamentoid) values (' Candelaria de la Frontera', 12);
insert into public.municipio (municipioname, departamentoid) values (' Chalchuapa', 12);
insert into public.municipio (municipioname, departamentoid) values (' Coatepeque', 12);
insert into public.municipio (municipioname, departamentoid) values (' El Congo', 12);
insert into public.municipio (municipioname, departamentoid) values (' El Porvenir', 12);
insert into public.municipio (municipioname, departamentoid) values (' Masahuat', 12);
insert into public.municipio (municipioname, departamentoid) values (' Metapán', 12);
insert into public.municipio (municipioname, departamentoid) values (' San Antonio Pajonal', 12);
insert into public.municipio (municipioname, departamentoid) values (' San Sebastián Salitrillo', 12);
insert into public.municipio (municipioname, departamentoid) values (' Santa Ana', 12);
insert into public.municipio (municipioname, departamentoid) values (' Santa Rosa Guachipilín', 12);
insert into public.municipio (municipioname, departamentoid) values (' Santiago de la Frontera', 12);
insert into public.municipio (municipioname, departamentoid) values (' Texistepeque', 12);
insert into public.municipio (municipioname, departamentoid) values (' Acajutla', 13);
insert into public.municipio (municipioname, departamentoid) values (' Armenia', 13);
insert into public.municipio (municipioname, departamentoid) values (' Caluco', 13);
insert into public.municipio (municipioname, departamentoid) values (' Cuisnahuat', 13);
insert into public.municipio (municipioname, departamentoid) values (' Izalco', 13);
insert into public.municipio (municipioname, departamentoid) values (' Juayúa', 13);
insert into public.municipio (municipioname, departamentoid) values (' Nahuizalco', 13);
insert into public.municipio (municipioname, departamentoid) values (' Nahulingo', 13);
insert into public.municipio (municipioname, departamentoid) values (' Salcoatitán', 13);
insert into public.municipio (municipioname, departamentoid) values (' San Antonio del Monte', 13);
insert into public.municipio (municipioname, departamentoid) values (' San Julián', 13);
insert into public.municipio (municipioname, departamentoid) values (' Santa Catarina Masahuat', 13);
insert into public.municipio (municipioname, departamentoid) values (' Santa Isabel Ishuatán', 13);
insert into public.municipio (municipioname, departamentoid) values (' Santo Domingo', 13);
insert into public.municipio (municipioname, departamentoid) values (' Sonsonate', 13);
insert into public.municipio (municipioname, departamentoid) values (' Sonzacate', 13);
insert into public.municipio (municipioname, departamentoid) values (' Alegría', 14);
insert into public.municipio (municipioname, departamentoid) values (' Berlín', 14);
insert into public.municipio (municipioname, departamentoid) values (' California', 14);
insert into public.municipio (municipioname, departamentoid) values (' Concepción Batres', 14);
insert into public.municipio (municipioname, departamentoid) values (' El Triunfo', 14);
insert into public.municipio (municipioname, departamentoid) values (' Ereguayquín', 14);
insert into public.municipio (municipioname, departamentoid) values (' Estanzuelas', 14);
insert into public.municipio (municipioname, departamentoid) values (' Jiquilisco', 14);
insert into public.municipio (municipioname, departamentoid) values (' Jucuapa', 14);
insert into public.municipio (municipioname, departamentoid) values (' Jucuarán', 14);
insert into public.municipio (municipioname, departamentoid) values (' Mercedes Umaña', 14);
insert into public.municipio (municipioname, departamentoid) values (' Nueva Granada', 14);
insert into public.municipio (municipioname, departamentoid) values (' Ozatlán', 14);
insert into public.municipio (municipioname, departamentoid) values (' Puerto El Triunfo', 14);
insert into public.municipio (municipioname, departamentoid) values (' San Agustín', 14);
insert into public.municipio (municipioname, departamentoid) values (' San Buenaventura', 14);
insert into public.municipio (municipioname, departamentoid) values (' San Dionisio', 14);
insert into public.municipio (municipioname, departamentoid) values (' San Francisco Javier', 14);
insert into public.municipio (municipioname, departamentoid) values (' Santa Elena', 14);
insert into public.municipio (municipioname, departamentoid) values (' Santa María', 14);
insert into public.municipio (municipioname, departamentoid) values (' Santiago de María', 14);
insert into public.municipio (municipioname, departamentoid) values (' Tecapán', 14);
insert into public.municipio (municipioname, departamentoid) values (' Usulután', 14);
